### ISSUE TITLE
Collision bug

### ISSUE THREAD

**Issue by JanSchollaert** [Brick-Studios/BrickEngine#22]
When you spam controls left and right (on multiplayer) sometimes the players glitch through each others collisions.

**Comment by LuukSantegoeds** [comment]
This bug can recreated when the gorilla stands on top of the panda. When they both jump at the same time, the panda catches up to the gorilla and they will through each other.

**Comment by LuukSantegoeds** [comment]
This was fixed "by accident" while tweaking movement

**Comment by Peter-JanGootzen** [comment]
The underlying bug was not fixed though, it just never occurs anymore because the movement doesn't allow for two players to collide like they used to.
